package Persistencia;
// Generated 08/11/2019 17:59:29 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase  implements java.io.Serializable {


     private Serializable tipoClase;
     private Clase clase;
     private Serializable vehiculos;
     private Serializable ageMin;
     private Set<Licencia> licencias = new HashSet<Licencia>(0);
     private Set<Clase> clases = new HashSet<Clase>(0);

    public Clase() {
    }

	
    public Clase(Serializable tipoClase, Serializable vehiculos, Serializable ageMin) {
        this.tipoClase = tipoClase;
        this.vehiculos = vehiculos;
        this.ageMin = ageMin;
    }
    public Clase(Serializable tipoClase, Clase clase, Serializable vehiculos, Serializable ageMin, Set<Licencia> licencias, Set<Clase> clases) {
       this.tipoClase = tipoClase;
       this.clase = clase;
       this.vehiculos = vehiculos;
       this.ageMin = ageMin;
       this.licencias = licencias;
       this.clases = clases;
    }
   
    public Serializable getTipoClase() {
        return this.tipoClase;
    }
    
    public void setTipoClase(Serializable tipoClase) {
        this.tipoClase = tipoClase;
    }
    public Clase getClase() {
        return this.clase;
    }
    
    public void setClase(Clase clase) {
        this.clase = clase;
    }
    public Serializable getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Serializable vehiculos) {
        this.vehiculos = vehiculos;
    }
    public Serializable getAgeMin() {
        return this.ageMin;
    }
    
    public void setAgeMin(Serializable ageMin) {
        this.ageMin = ageMin;
    }
    public Set<Licencia> getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Set<Licencia> licencias) {
        this.licencias = licencias;
    }
    public Set<Clase> getClases() {
        return this.clases;
    }
    
    public void setClases(Set<Clase> clases) {
        this.clases = clases;
    }




}


