package Persistencia;
// Generated 08/11/2019 17:59:29 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Costo generated by hbm2java
 */
public class Costo  implements java.io.Serializable {


     private Serializable id;
     private Serializable clase;
     private Serializable anios;
     private Serializable precio;
     private Set<Licencia> licencias = new HashSet<Licencia>(0);

    public Costo() {
    }

	
    public Costo(Serializable id, Serializable clase, Serializable anios, Serializable precio) {
        this.id = id;
        this.clase = clase;
        this.anios = anios;
        this.precio = precio;
    }
    public Costo(Serializable id, Serializable clase, Serializable anios, Serializable precio, Set<Licencia> licencias) {
       this.id = id;
       this.clase = clase;
       this.anios = anios;
       this.precio = precio;
       this.licencias = licencias;
    }
   
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(Serializable id) {
        this.id = id;
    }
    public Serializable getClase() {
        return this.clase;
    }
    
    public void setClase(Serializable clase) {
        this.clase = clase;
    }
    public Serializable getAnios() {
        return this.anios;
    }
    
    public void setAnios(Serializable anios) {
        this.anios = anios;
    }
    public Serializable getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Serializable precio) {
        this.precio = precio;
    }
    public Set<Licencia> getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Set<Licencia> licencias) {
        this.licencias = licencias;
    }




}


