package Persistencia;
// Generated 08/11/2019 17:59:29 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Serializable documento;
     private String nombre;
     private String apellido;
     private Serializable tipoDeSangre;
     private Serializable direccion;
     private Serializable fechaDeNacimiento;
     private Serializable donante;
     private Serializable tipoDocumento;
     private Set<Licencia> licencias = new HashSet<Licencia>(0);

    public Persona() {
    }

	
    public Persona(Serializable documento, String nombre, String apellido, Serializable tipoDeSangre, Serializable direccion, Serializable fechaDeNacimiento, Serializable donante, Serializable tipoDocumento) {
        this.documento = documento;
        this.nombre = nombre;
        this.apellido = apellido;
        this.tipoDeSangre = tipoDeSangre;
        this.direccion = direccion;
        this.fechaDeNacimiento = fechaDeNacimiento;
        this.donante = donante;
        this.tipoDocumento = tipoDocumento;
    }
    public Persona(Serializable documento, String nombre, String apellido, Serializable tipoDeSangre, Serializable direccion, Serializable fechaDeNacimiento, Serializable donante, Serializable tipoDocumento, Set<Licencia> licencias) {
       this.documento = documento;
       this.nombre = nombre;
       this.apellido = apellido;
       this.tipoDeSangre = tipoDeSangre;
       this.direccion = direccion;
       this.fechaDeNacimiento = fechaDeNacimiento;
       this.donante = donante;
       this.tipoDocumento = tipoDocumento;
       this.licencias = licencias;
    }
   
    public Serializable getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(Serializable documento) {
        this.documento = documento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Serializable getTipoDeSangre() {
        return this.tipoDeSangre;
    }
    
    public void setTipoDeSangre(Serializable tipoDeSangre) {
        this.tipoDeSangre = tipoDeSangre;
    }
    public Serializable getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Serializable direccion) {
        this.direccion = direccion;
    }
    public Serializable getFechaDeNacimiento() {
        return this.fechaDeNacimiento;
    }
    
    public void setFechaDeNacimiento(Serializable fechaDeNacimiento) {
        this.fechaDeNacimiento = fechaDeNacimiento;
    }
    public Serializable getDonante() {
        return this.donante;
    }
    
    public void setDonante(Serializable donante) {
        this.donante = donante;
    }
    public Serializable getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(Serializable tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public Set<Licencia> getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Set<Licencia> licencias) {
        this.licencias = licencias;
    }




}


