package Persistencia;
// Generated 08/11/2019 17:59:29 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Serializable idUser;
     private Serializable username;
     private Serializable password;
     private Serializable privilegie;
     private Set<Licencia> licencias = new HashSet<Licencia>(0);

    public User() {
    }

	
    public User(Serializable idUser, Serializable username, Serializable password, Serializable privilegie) {
        this.idUser = idUser;
        this.username = username;
        this.password = password;
        this.privilegie = privilegie;
    }
    public User(Serializable idUser, Serializable username, Serializable password, Serializable privilegie, Set<Licencia> licencias) {
       this.idUser = idUser;
       this.username = username;
       this.password = password;
       this.privilegie = privilegie;
       this.licencias = licencias;
    }
   
    public Serializable getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Serializable idUser) {
        this.idUser = idUser;
    }
    public Serializable getUsername() {
        return this.username;
    }
    
    public void setUsername(Serializable username) {
        this.username = username;
    }
    public Serializable getPassword() {
        return this.password;
    }
    
    public void setPassword(Serializable password) {
        this.password = password;
    }
    public Serializable getPrivilegie() {
        return this.privilegie;
    }
    
    public void setPrivilegie(Serializable privilegie) {
        this.privilegie = privilegie;
    }
    public Set<Licencia> getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Set<Licencia> licencias) {
        this.licencias = licencias;
    }




}


