package Persistencia;
// Generated 08/11/2019 17:59:29 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Vigencia generated by hbm2java
 */
public class Vigencia  implements java.io.Serializable {


     private Serializable idVigencia;
     private Serializable condicion;
     private Serializable duracion;
     private Set<Licencia> licencias = new HashSet<Licencia>(0);

    public Vigencia() {
    }

	
    public Vigencia(Serializable idVigencia, Serializable condicion, Serializable duracion) {
        this.idVigencia = idVigencia;
        this.condicion = condicion;
        this.duracion = duracion;
    }
    public Vigencia(Serializable idVigencia, Serializable condicion, Serializable duracion, Set<Licencia> licencias) {
       this.idVigencia = idVigencia;
       this.condicion = condicion;
       this.duracion = duracion;
       this.licencias = licencias;
    }
   
    public Serializable getIdVigencia() {
        return this.idVigencia;
    }
    
    public void setIdVigencia(Serializable idVigencia) {
        this.idVigencia = idVigencia;
    }
    public Serializable getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(Serializable condicion) {
        this.condicion = condicion;
    }
    public Serializable getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Serializable duracion) {
        this.duracion = duracion;
    }
    public Set<Licencia> getLicencias() {
        return this.licencias;
    }
    
    public void setLicencias(Set<Licencia> licencias) {
        this.licencias = licencias;
    }




}


