/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author usser
 */
public class ModificarDatosUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ModificarDatosUsuario
     */
    public ModificarDatosUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        contraseñaRepetirOperador = new javax.swing.JLabel();
        nombreOperadorModif = new javax.swing.JTextField();
        dniOperadorModif = new javax.swing.JTextField();
        contraseñaOperadorModif = new javax.swing.JTextField();
        apellidoOperadorModif = new javax.swing.JTextField();
        nombreUsuarioOperadorModif = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        repetirContraseñaOperadorModif = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RegistrarOperadorModif = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CancelarOperadorModif = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        jLabel1.setText("Modificar Datos Operador");

        contraseñaRepetirOperador.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        contraseñaRepetirOperador.setText("Repetir Contraseña");

        nombreOperadorModif.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N

        dniOperadorModif.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N

        contraseñaOperadorModif.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N

        apellidoOperadorModif.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N

        nombreUsuarioOperadorModif.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        jLabel2.setText("Nombre");

        repetirContraseñaOperadorModif.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        jLabel3.setText("Apellido");

        RegistrarOperadorModif.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        RegistrarOperadorModif.setText("Registrar");

        jLabel4.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        jLabel4.setText("DNI");

        CancelarOperadorModif.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        CancelarOperadorModif.setText("Cancelar");

        jLabel5.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        jLabel5.setText("Nombre de Usuario");

        jLabel6.setFont(new java.awt.Font("Eras Light ITC", 0, 16)); // NOI18N
        jLabel6.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel1)
                .addContainerGap(247, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(RegistrarOperadorModif)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(19, 19, 19)))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dniOperadorModif)
                                .addComponent(nombreOperadorModif, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                .addComponent(contraseñaOperadorModif))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)
                        .addComponent(contraseñaRepetirOperador))
                    .addGap(38, 38, 38)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(apellidoOperadorModif)
                            .addComponent(nombreUsuarioOperadorModif)
                            .addComponent(repetirContraseñaOperadorModif, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                        .addComponent(CancelarOperadorModif))
                    .addGap(53, 53, 53)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(410, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(nombreOperadorModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(apellidoOperadorModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(dniOperadorModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombreUsuarioOperadorModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(39, 39, 39)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(contraseñaRepetirOperador)
                        .addComponent(contraseñaOperadorModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(repetirContraseñaOperadorModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RegistrarOperadorModif)
                        .addComponent(CancelarOperadorModif))
                    .addGap(76, 76, 76)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarDatosUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarOperadorModif;
    private javax.swing.JButton RegistrarOperadorModif;
    private javax.swing.JTextField apellidoOperadorModif;
    private javax.swing.JTextField contraseñaOperadorModif;
    private javax.swing.JLabel contraseñaRepetirOperador;
    private javax.swing.JTextField dniOperadorModif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombreOperadorModif;
    private javax.swing.JTextField nombreUsuarioOperadorModif;
    private javax.swing.JTextField repetirContraseñaOperadorModif;
    // End of variables declaration//GEN-END:variables
}
